// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD0RgMMI9OE1Dd_5SqB5WS7TVN8ovkb6Y',
    appId: '1:1047945808084:web:22bf2876eb1660ec669341',
    messagingSenderId: '1047945808084',
    projectId: 'saxat-savita-flutter',
    authDomain: 'saxat-savita-flutter.firebaseapp.com',
    storageBucket: 'saxat-savita-flutter.firebasestorage.app',
    measurementId: 'G-BWLT77Z355',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg0r8Pny9Kc4F89JzP3bWbyrFwUylRQvg',
    appId: '1:1047945808084:android:8bf8721ad3acbecd669341',
    messagingSenderId: '1047945808084',
    projectId: 'saxat-savita-flutter',
    storageBucket: 'saxat-savita-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv46ORVkMOUxZGJEK9-8hdJWjlAkKDsgc',
    appId: '1:1047945808084:ios:98214531b0dccdd1669341',
    messagingSenderId: '1047945808084',
    projectId: 'saxat-savita-flutter',
    storageBucket: 'saxat-savita-flutter.firebasestorage.app',
    iosClientId: '1047945808084-1apup4nlgd0qttdn2lp5kvhfrnsao00u.apps.googleusercontent.com',
    iosBundleId: 'com.farenidham.books.saxatsavitaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv46ORVkMOUxZGJEK9-8hdJWjlAkKDsgc',
    appId: '1:1047945808084:ios:98214531b0dccdd1669341',
    messagingSenderId: '1047945808084',
    projectId: 'saxat-savita-flutter',
    storageBucket: 'saxat-savita-flutter.firebasestorage.app',
    iosClientId: '1047945808084-1apup4nlgd0qttdn2lp5kvhfrnsao00u.apps.googleusercontent.com',
    iosBundleId: 'com.farenidham.books.saxatsavitaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD0RgMMI9OE1Dd_5SqB5WS7TVN8ovkb6Y',
    appId: '1:1047945808084:web:575b2b2797908bb2669341',
    messagingSenderId: '1047945808084',
    projectId: 'saxat-savita-flutter',
    authDomain: 'saxat-savita-flutter.firebaseapp.com',
    storageBucket: 'saxat-savita-flutter.firebasestorage.app',
    measurementId: 'G-Y9M2LFXT3W',
  );
}
