// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoaqkdcr4QjPCC0RCeXBkHs1_o4S7TDAU',
    appId: '1:39080773295:web:aa710ce34567667451f65a',
    messagingSenderId: '39080773295',
    projectId: 'saxat-savita-crashanalytics',
    authDomain: 'saxat-savita-crashanalytics.firebaseapp.com',
    databaseURL:
        'https://saxat-savita-crashanalytics-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saxat-savita-crashanalytics.firebasestorage.app',
    measurementId: 'G-CKN0171NWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDewIEmCaTx8I0ScnTWS8eeHghun3kSKus',
    appId: '1:39080773295:android:34dd117ce8c4e76351f65a',
    messagingSenderId: '39080773295',
    projectId: 'saxat-savita-crashanalytics',
    databaseURL:
        'https://saxat-savita-crashanalytics-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saxat-savita-crashanalytics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZ0aibkjqCH12L0ZOpIe_Z0Tgz7JPWMA',
    appId: '1:39080773295:ios:4e8e19d9e7db917051f65a',
    messagingSenderId: '39080773295',
    projectId: 'saxat-savita-crashanalytics',
    databaseURL:
        'https://saxat-savita-crashanalytics-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saxat-savita-crashanalytics.firebasestorage.app',
    androidClientId:
        '39080773295-7f1raj93kns2ipjebqrulgspobfstdr2.apps.googleusercontent.com',
    iosClientId:
        '39080773295-fedihdmhcam4ihnkvjspv3olacdvl9ia.apps.googleusercontent.com',
    iosBundleId: 'com.astound.SaxatSavita',
  );
}
