#!/usr/bin/env python3
"""Build the v1 reviewed seed quiz bank from existing kiran JSON."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets/book/saxatsavita/quizzes/kiran_quizzes.json"


def g(*codes: int) -> str:
    return "".join(chr(c) for c in codes)


def load_kiran(index: int) -> dict:
    path = ROOT / f"assets/book/saxatsavita/part1/kiran_{index}.json"
    return json.loads(path.read_text(encoding="utf-8"))


def must_find(haystack: str, needle: str) -> str:
    if needle not in haystack:
        raise SystemExit(f"missing {needle!r} in source")
    return needle


def unique_places() -> list[str]:
    data = json.loads(
        (ROOT / "assets/book/saxatsavita/_all_kirans_.json").read_text(encoding="utf-8")
    )
    places: list[str] = []
    for item in data.get("list", data if isinstance(data, list) else []):
        if not isinstance(item, dict):
            continue
        place = (item.get("place") or "").strip()
        if place and place not in places:
            places.append(place)
        for extra in item.get("places") or []:
            extra = str(extra).strip()
            if extra and extra not in places:
                places.append(extra)
    return places


def strip_html(text: str) -> str:
    if "</b>" in text:
        text = text.split("</b>", 1)[-1]
    return text.replace("<b>", "").strip()


def main() -> None:
    k1, k2, k3 = load_kiran(1), load_kiran(2), load_kiran(3)
    blob1 = json.dumps(k1, ensure_ascii=False)
    blob2 = json.dumps(k2, ensure_ascii=False)
    blob3 = json.dumps(k3, ensure_ascii=False)

    pipelana = must_find(blob1, g(0x0AAA, 0x0AC0, 0x0AAA, 0x0AB2, 0x0ABE, 0x0AA3, 0x0ABE))
    places = [p for p in unique_places() if p != pipelana][:3]
    if len(places) < 3:
        raise SystemExit("need 3 distractor places")

    shuddha = must_find(
        blob1,
        g(
            0x0AB6,
            0x0AC1,
            0x0AA6,
            0x0ACD,
            0x0AA7,
            0x20,
            0x0A9A,
            0x0AC8,
            0x0AA4,
            0x0AA8,
            0x0ACD,
            0x0AAF,
            0x20,
            0x0AAC,
            0x0ACD,
            0x0AB0,
            0x0AB9,
            0x0ACD,
            0x0AAE,
        ),
    )
    gold = must_find(
        blob1,
        g(
            0x0AB8,
            0x0ACB,
            0x0AA8,
            0x0AC1,
            0x0A82,
            0x20,
            0x0A85,
            0x0AA8,
            0x0AC7,
            0x20,
            0x0AB8,
            0x0ACD,
            0x0AA4,
            0x0ACD,
            0x0AB0,
            0x0AC0,
        ),
    )
    anvay = must_find(
        blob2,
        g(
            0x0AA4,
            0x0ACD,
            0x0AB0,
            0x0AA3,
            0x0A97,
            0x0AC1,
            0x0AA3,
            0x0AAE,
            0x0AAF,
            0x0AAA,
            0x0AA3,
            0x0AC1,
            0x0A82,
        ),
    )
    vyatirek = must_find(
        blob2,
        g(
            0x0AA4,
            0x0ACD,
            0x0AB0,
            0x0AA3,
            0x0A97,
            0x0AC1,
            0x0AA3,
            0x0AB0,
            0x0AB9,
            0x0ABF,
            0x0AA4,
            0x0AAA,
            0x0AA3,
            0x0AC1,
            0x0A82,
        ),
    )
    anvay_to_vyatirek = must_find(
        blob2,
        g(
            0x0A85,
            0x0AA8,
            0x0ACD,
            0x0AB5,
            0x0AAF,
            0x0AAE,
            0x0ABE,
            0x0A82,
            0x0AA5,
            0x0AC0,
            0x20,
            0x0AB5,
            0x0ACD,
            0x0AAF,
            0x0AA4,
            0x0ABF,
            0x0AB0,
            0x0AC7,
            0x0A95,
        ),
    )
    dharma_palvo = must_find(
        blob3,
        g(0x0AA7, 0x0AB0, 0x0ACD, 0x0AAE, 0x20, 0x0AAA, 0x0ABE, 0x0AB3, 0x0AB5, 0x0ACB),
    )
    sambandh = must_find(
        blob3,
        g(
            0x0AA7,
            0x0AB0,
            0x0ACD,
            0x0AAE,
            0x20,
            0x0AAA,
            0x0ABE,
            0x0AB3,
            0x0AA8,
            0x0ABE,
            0x0AB0,
            0x0AA8,
            0x0ACB,
            0x20,
            0x0AB8,
            0x0A82,
            0x0AAC,
            0x0A82,
            0x0AA7,
            0x20,
            0x0AB0,
            0x0ABE,
            0x0A96,
            0x0AB5,
            0x0ACB,
        ),
    )
    varne = must_find(
        blob3,
        g(
            0x0AB5,
            0x0AB0,
            0x0AA8,
            0x0AC7,
            0x20,
            0x0AA0,
            0x0AC7,
            0x0A95,
            0x0ABE,
            0x0AA3,
            0x0AC7,
        ),
    )
    janaiya = must_find(
        blob3,
        g(
            0x0A9C,
            0x0ABE,
            0x0AA8,
            0x0AC8,
            0x0AAF,
            0x0ABE,
            0x0AA8,
            0x0AC7,
            0x20,
            0x0AA0,
            0x0AC7,
            0x0A95,
            0x0ABE,
            0x0AA3,
            0x0AC7,
        ),
    )

    q = lambda *codes: g(*codes) + "?"

    bank = {
        "quizzes": [
            {
                "part": 1,
                "kiranIndex": 1,
                "version": 1,
                "locale": "gu",
                "questions": [
                    {
                        "id": "p1-1-q1",
                        "prompt": q(
                            0x0A86,
                            0x20,
                            0x0A95,
                            0x0AA5,
                            0x0ABE,
                            0x20,
                            0x0A95,
                            0x0ACD,
                            0x0AAF,
                            0x0ABE,
                            0x0A82,
                            0x20,
                            0x0AB5,
                            0x0A82,
                            0x0A9A,
                            0x0ABE,
                            0x0A88,
                        ),
                        "options": [pipelana, *places],
                        "correctIndex": 0,
                        "explanation": (k1["meta"].get("locations") or [pipelana])[0],
                        "sourceHint": g(0x0AB8, 0x0ACD, 0x0AA5, 0x0AB3),
                    },
                    {
                        "id": "p1-1-q2",
                        "prompt": q(
                            0x0AAA,
                            0x0ACD,
                            0x0AB0,
                            0x0A95,
                            0x0AC3,
                            0x0AA4,
                            0x0ABF,
                            0x0AAA,
                            0x0AC1,
                            0x0AB0,
                            0x0AC1,
                            0x0AB7,
                            0x0AA5,
                            0x0AC0,
                            0x20,
                            0x0AAA,
                            0x0AB0,
                            0x20,
                            0x0A95,
                            0x0ACB,
                            0x0AA8,
                            0x0AC7,
                            0x20,
                            0x0A8F,
                            0x0A95,
                            0x20,
                            0x0AB8,
                            0x0AA4,
                            0x0ACD,
                            0x0AAF,
                            0x20,
                            0x0AAE,
                            0x0ABE,
                            0x0AA8,
                            0x0AB5,
                            0x0AC1,
                            0x0A82,
                        ),
                        "options": [
                            shuddha,
                            g(0x0AA4, 0x0ACD, 0x0AB0, 0x0AA3, 0x20, 0x0A97, 0x0AC1, 0x0AA3),
                            g(
                                0x0AA7,
                                0x0AB0,
                                0x0ACD,
                                0x0AAE,
                                0x0AA8,
                                0x0ABF,
                                0x0AB7,
                                0x0ACD,
                                0x0AA0,
                                0x0ABE,
                            ),
                            g(0x0A85, 0x0AA8, 0x0ACD, 0x0AB5, 0x0AAF),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k1["meta"]["summary"][0]),
                        "sourceHint": g(0x0AAE, 0x0AC2, 0x0AB3, 0x20, 0x0A89, 0x0AAA, 0x0AA6, 0x0AC7, 0x0AB6),
                    },
                    {
                        "id": "p1-1-q3",
                        "prompt": q(
                            0x0AB6,
                            0x0AC1,
                            0x0AA6,
                            0x0ACD,
                            0x0AA7,
                            0x20,
                            0x0A9A,
                            0x0AC8,
                            0x0AA4,
                            0x0AA8,
                            0x0ACD,
                            0x0AAF,
                            0x0AAC,
                            0x0ACD,
                            0x0AB0,
                            0x0AB9,
                            0x0ACD,
                            0x0AAE,
                            0x20,
                            0x0A93,
                            0x0AB3,
                            0x0A96,
                            0x0ABE,
                            0x0AAF,
                            0x20,
                            0x0AA4,
                            0x0ACB,
                            0x20,
                            0x0AB6,
                            0x0AC1,
                            0x0A82,
                            0x20,
                            0x0AAC,
                            0x0A82,
                            0x0AA7,
                            0x0AA8,
                            0x20,
                            0x0AA8,
                            0x20,
                            0x0A95,
                            0x0AB0,
                            0x0AC7,
                        ),
                        "options": [
                            gold,
                            g(
                                0x0AB6,
                                0x0ABE,
                                0x0AB8,
                                0x0ACD,
                                0x0AA4,
                                0x0ACD,
                                0x0AB0,
                                0x20,
                                0x0A85,
                                0x0AA8,
                                0x0AC7,
                                0x20,
                                0x0AB8,
                                0x0A82,
                                0x0AA4,
                            ),
                            g(
                                0x0A85,
                                0x0AA8,
                                0x0ACD,
                                0x0AB5,
                                0x0AAF,
                                0x20,
                                0x0A85,
                                0x0AA8,
                                0x0AC7,
                                0x20,
                                0x0AB5,
                                0x0ACD,
                                0x0AAF,
                                0x0AA4,
                                0x0ABF,
                                0x0AB0,
                                0x0AC7,
                                0x0A95,
                            ),
                            g(
                                0x0AA7,
                                0x0AB0,
                                0x0ACD,
                                0x0AAE,
                                0x20,
                                0x0A85,
                                0x0AA8,
                                0x0AC7,
                                0x20,
                                0x0AB8,
                                0x0ACD,
                                0x0AB5,
                                0x0AB0,
                                0x0AC2,
                                0x0AAA,
                            ),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k1["meta"]["summary"][3]),
                        "sourceHint": g(0x0AAE, 0x0AC1, 0x0A95, 0x0ACD, 0x0AA4, 0x0ABF),
                    },
                ],
            },
            {
                "part": 1,
                "kiranIndex": 2,
                "version": 1,
                "locale": "gu",
                "questions": [
                    {
                        "id": "p1-2-q1",
                        "prompt": q(
                            0x0A85,
                            0x0AA8,
                            0x0ACD,
                            0x0AB5,
                            0x0AAF,
                            0x0AAA,
                            0x0AA3,
                            0x0AC1,
                            0x0A82,
                            0x20,
                            0x0A8F,
                            0x0A9F,
                            0x0AB2,
                            0x0AC7,
                            0x20,
                            0x0AB6,
                            0x0AC1,
                            0x0A82,
                        ),
                        "options": [
                            anvay,
                            vyatirek,
                            g(
                                0x0A85,
                                0x0A82,
                                0x0AA4,
                                0x0AB0,
                                0x0ACD,
                                0x0AAF,
                                0x0ABE,
                                0x0AAE,
                                0x0AC0,
                                0x0AAA,
                                0x0AA3,
                                0x0AC1,
                                0x0A82,
                            ),
                            g(
                                0x0AB5,
                                0x0ACD,
                                0x0AAF,
                                0x0ABE,
                                0x0AAA,
                                0x0A95,
                                0x0AAA,
                                0x0AA3,
                                0x0AC1,
                                0x0A82,
                            ),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k2["meta"]["summary"][0]),
                        "sourceHint": g(0x0A85, 0x0AA8, 0x0ACD, 0x0AB5, 0x0AAF),
                    },
                    {
                        "id": "p1-2-q2",
                        "prompt": q(
                            0x0A87,
                            0x0A82,
                            0x0AA6,
                            0x0ACD,
                            0x0AB0,
                            0x0ABF,
                            0x0AAF,
                            0x0ACB,
                            0x0AA8,
                            0x0AC7,
                            0x20,
                            0x0A9C,
                            0x0AC0,
                            0x0AA4,
                            0x0AB5,
                            0x0ABE,
                            0x0AA8,
                            0x0AC0,
                            0x20,
                            0x0AAF,
                            0x0AC1,
                            0x0A95,
                            0x0ACD,
                            0x0AA4,
                            0x0ABF,
                            0x20,
                            0x0A95,
                            0x0ACD,
                            0x0AAF,
                            0x0ABE,
                            0x0A82,
                            0x0AA5,
                            0x0AC0,
                            0x20,
                            0x0A97,
                            0x0ACD,
                            0x0AB0,
                            0x0AB9,
                            0x0AA3,
                            0x20,
                            0x0A95,
                            0x0AB0,
                            0x0AB5,
                            0x0AC0,
                        ),
                        "options": [
                            g(0x0AB8, 0x0A82, 0x0AA4, 0x20, 0x0AA5, 0x0A95, 0x0AC0),
                            g(
                                0x0AB6,
                                0x0ABE,
                                0x0AB8,
                                0x0ACD,
                                0x0AA4,
                                0x0ACD,
                                0x0AB0,
                                0x20,
                                0x0AA5,
                                0x0A95,
                                0x0AC0,
                            ),
                            g(
                                0x0A87,
                                0x0A82,
                                0x0AA6,
                                0x0ACD,
                                0x0AB0,
                                0x0ABF,
                                0x0AAF,
                                0x0ACB,
                                0x20,
                                0x0AA5,
                                0x0A95,
                                0x0AC0,
                            ),
                            g(
                                0x0AAF,
                                0x0ACB,
                                0x0A97,
                                0x0A95,
                                0x0AB3,
                                0x0ABE,
                                0x20,
                                0x0AA5,
                                0x0A95,
                                0x0AC0,
                            ),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k2["meta"]["summary"][3]),
                        "sourceHint": g(0x0AB8, 0x0A82, 0x0AA4),
                    },
                    {
                        "id": "p1-2-q3",
                        "prompt": q(
                            0x0AAD,
                            0x0AAE,
                            0x0AB0,
                            0x0AC0,
                            0x0AA8,
                            0x0ABE,
                            0x20,
                            0x0AB8,
                            0x0A82,
                            0x0A97,
                            0x0AC7,
                            0x20,
                            0x0A87,
                            0x0AAF,
                            0x0AB3,
                            0x0AAE,
                            0x0ABE,
                            0x0A82,
                            0x20,
                            0x0AB6,
                            0x0AC1,
                            0x0A82,
                            0x20,
                            0x0AA5,
                            0x0ABE,
                            0x0AAF,
                        ),
                        "options": [
                            anvay_to_vyatirek + " " + g(0x0AA5, 0x0ABE, 0x0AAF),
                            g(
                                0x0AA4,
                                0x0ACD,
                                0x0AB0,
                                0x0AA3,
                                0x0A97,
                                0x0AC1,
                                0x0AA3,
                                0x20,
                                0x0AB5,
                                0x0AA7,
                                0x0AC7,
                            ),
                            g(
                                0x0AB6,
                                0x0ABE,
                                0x0AB8,
                                0x0ACD,
                                0x0AA4,
                                0x0ACD,
                                0x0AB0,
                                0x0AA8,
                                0x0ACB,
                                0x20,
                                0x0AAE,
                                0x0AB9,
                                0x0ABF,
                                0x0AAE,
                                0x0ABE,
                                0x20,
                                0x0A98,
                                0x0A9F,
                                0x0AC7,
                            ),
                            g(
                                0x0AB0,
                                0x0ABE,
                                0x0AB8,
                                0x0AAE,
                                0x0A82,
                                0x0AA1,
                                0x0AB3,
                                0x20,
                                0x0AAC,
                                0x0A82,
                                0x0AA7,
                                0x20,
                                0x0AA5,
                                0x0ABE,
                                0x0AAF,
                            ),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k2["meta"]["summary"][4]),
                        "sourceHint": g(0x0A87, 0x0AAF, 0x0AB3),
                    },
                ],
            },
            {
                "part": 1,
                "kiranIndex": 3,
                "version": 1,
                "locale": "gu",
                "questions": [
                    {
                        "id": "p1-3-q1",
                        "prompt": q(
                            0x0AA7,
                            0x0AB0,
                            0x0ACD,
                            0x0AAE,
                            0x0AA8,
                            0x0ABF,
                            0x0AB7,
                            0x0ACD,
                            0x0AA0,
                            0x0ABE,
                            0x20,
                            0x0A8F,
                            0x0A9F,
                            0x0AB2,
                            0x0AC7,
                            0x20,
                            0x0AB6,
                            0x0AC1,
                            0x0A82,
                        ),
                        "options": [
                            dharma_palvo,
                            sambandh,
                            g(
                                0x0AB6,
                                0x0ABE,
                                0x0AB8,
                                0x0ACD,
                                0x0AA4,
                                0x0ACD,
                                0x0AB0,
                                0x20,
                                0x0AB5,
                                0x0ABE,
                                0x0A82,
                                0x0A9A,
                                0x0AB5,
                                0x0AC1,
                                0x0A82,
                            ),
                            g(
                                0x0A87,
                                0x0A82,
                                0x0AA6,
                                0x0ACD,
                                0x0AB0,
                                0x0ABF,
                                0x0AAF,
                                0x0ACB,
                                0x20,
                                0x0A9C,
                                0x0AC0,
                                0x0AA4,
                                0x0AB5,
                                0x0AC0,
                            ),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k3["meta"]["summary"][1]),
                        "sourceHint": g(0x0A85, 0x0AB0, 0x0ACD, 0x0AA5),
                    },
                    {
                        "id": "p1-3-q2",
                        "prompt": q(
                            0x0AB8,
                            0x0ACD,
                            0x0AB5,
                            0x0AB0,
                            0x0AC2,
                            0x0AAA,
                            0x0AA8,
                            0x0ABF,
                            0x0AB7,
                            0x0ACD,
                            0x0AA0,
                            0x0ABE,
                            0x20,
                            0x0A8F,
                            0x0A9F,
                            0x0AB2,
                            0x0AC7,
                            0x20,
                            0x0AB6,
                            0x0AC1,
                            0x0A82,
                        ),
                        "options": [
                            sambandh,
                            dharma_palvo,
                            g(
                                0x0AA4,
                                0x0ACD,
                                0x0AB0,
                                0x0AA3,
                                0x0A97,
                                0x0AC1,
                                0x0AA3,
                                0x20,
                                0x0AA4,
                                0x0ACD,
                                0x0AAF,
                                0x0ABE,
                                0x0A97,
                            ),
                            g(
                                0x0A95,
                                0x0AA5,
                                0x0ABE,
                                0x20,
                                0x0AB8,
                                0x0ABE,
                                0x0A82,
                                0x0AAD,
                                0x0AB3,
                                0x0AB5,
                                0x0AC0,
                            ),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k3["meta"]["summary"][1]),
                        "sourceHint": g(0x0A85, 0x0AB0, 0x0ACD, 0x0AA5),
                    },
                    {
                        "id": "p1-3-q3",
                        "prompt": q(
                            0x0AB8,
                            0x0ACD,
                            0x0AB5,
                            0x0AB0,
                            0x0AC2,
                            0x0AAA,
                            0x0AA8,
                            0x0ABF,
                            0x0AB7,
                            0x0ACD,
                            0x0AA0,
                            0x0ABE,
                            0x20,
                            0x0A95,
                            0x0ACB,
                            0x0AA8,
                            0x0AC7,
                            0x20,
                            0x0AA0,
                            0x0AC7,
                            0x0A95,
                            0x0ABE,
                            0x0AA3,
                            0x0AC7,
                            0x20,
                            0x0A9B,
                            0x0AC7,
                        ),
                        "options": [
                            varne,
                            janaiya,
                            g(
                                0x0AB6,
                                0x0ABE,
                                0x0AB8,
                                0x0ACD,
                                0x0AA4,
                                0x0ACD,
                                0x0AB0,
                                0x0AA8,
                                0x0AC7,
                                0x20,
                                0x0AA0,
                                0x0AC7,
                                0x0A95,
                                0x0ABE,
                                0x0AA3,
                                0x0AC7,
                            ),
                            g(
                                0x0A87,
                                0x0A82,
                                0x0AA6,
                                0x0ACD,
                                0x0AB0,
                                0x0ABF,
                                0x0AAF,
                                0x0ACB,
                                0x0AA8,
                                0x0AC7,
                                0x20,
                                0x0AA0,
                                0x0AC7,
                                0x0A95,
                                0x0ABE,
                                0x0AA3,
                                0x0AC7,
                            ),
                        ],
                        "correctIndex": 0,
                        "explanation": strip_html(k3["meta"]["summary"][2]),
                        "sourceHint": g(0x0AB8, 0x0ACD, 0x0AA5, 0x0ABE, 0x0AA8),
                    },
                ],
            },
        ]
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(bank, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    for quiz in bank["quizzes"]:
        print(f"--- kiran {quiz['kiranIndex']} ---")
        for item in quiz["questions"]:
            print(item["prompt"])
            print(" ", item["options"])


if __name__ == "__main__":
    main()
